# spot-cluster.yaml

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-1
  region: us-east-1

managedNodeGroups:
- name: expense
  instanceTypes: m5.large
  diseredCapacity: 3
  spot: true


# # `instanceTypes` defaults to [`m5.large`]
# - name: spot-2
#   spot: true

# # On-Demand instances
# - name: on-demand
#   instanceTypes: ["c3.large", "c4.large", "c5.large"]